### ISSUE TITLE
CI for CI?

### ISSUE THREAD

**Issue by musabmasood** [PaytmLabs/docker-kubernetes-ci#1]
Lets add a CI building the CI image ;)

**Comment by maxbrunet** [comment]
It already uses Docker Hub Automated Builds:
* https://docs.docker.com/docker-hub/builds/
* https://docs.docker.com/docker-hub/builds/automated-testing/

https://hub.docker.com/r/paytmcanada/kubernetes-ci/builds

**Comment by musabmasood** [comment]
> It already uses Docker Hub Automated Builds:
> 
> * https://docs.docker.com/docker-hub/builds/
> * https://docs.docker.com/docker-hub/builds/automated-testing/
> 
> https://hub.docker.com/r/paytmcanada/kubernetes-ci/builds

Cool, I didn't know that.
